/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sathish' at '1/18/17 8:01 PM' with Gradle 2.14.1
 *
 * @author Sathish, @date 1/18/17 8:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
